// automatically generated by the FlatBuffers compiler, do not modify

package Contract;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final byte NONE = 0;
  public static final byte SelectAllSound = 1;
  public static final byte SelectSoundIds = 2;
  public static final byte CreateSound = 3;
  public static final byte ModifySound = 4;
  public static final byte DeleteSound = 5;
  public static final byte Sound = 6;

  public static final String[] names = { "NONE", "SelectAllSound", "SelectSoundIds", "CreateSound", "ModifySound", "DeleteSound", "Sound", };

  public static String name(int e) { return names[e]; }
}

